[package]
name = "scisight-keep-alive"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
reqwest = { version = "0.11.22", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.33.0", features = ["full"] }
