train_texts = []
train_texts.extend([
    # ecology workers
    "I work in a wildlife rehabilitation center caring for injured animals.",
    "My daily tasks involve monitoring air and water quality in the city.",
    "I assist in maintaining the local community garden to promote biodiversity.",
    "My job involves overseeing waste management protocols to minimize pollution.",
    "I work on projects that aim to conserve the natural habitats of endangered species.",
    "I'm involved in initiatives that promote sustainable farming practices.",
    "My role includes educating the public on the importance of water conservation.",
    "I help in organizing clean-up drives in various polluted areas in the city.",
    "I support initiatives that aim to reduce the carbon footprint of businesses.",
    "My daily tasks involve monitoring the health of flora and fauna in protected areas.",
    "I assist in implementing conservation policies in our local community.",
    "I work closely with environmental scientists to understand the impacts of climate change.",
    "I'm part of a team that develops educational materials on environmental conservation.",
    "I assist in planning and executing reforestation projects in deforested areas.",
    "My job involves conducting environmental impact assessments for new construction projects.",
    "I help in the rehabilitation of wildlife affected by habitat destruction.",
    "I'm involved in creating awareness campaigns about the importance of biodiversity.",
    "I work on developing sustainable solutions for waste disposal in urban areas.",
    "I assist in the planning and implementation of community-based conservation projects.",
    "My role involves promoting the use of renewable energy sources within the community.",
    "I work with local schools to educate students about the importance of environmental conservation.",
    "I'm involved in projects that aim to restore and preserve wetlands and other sensitive ecosystems.",
    "I assist in conducting surveys to monitor the population of endangered species in the area.",
    "I work with a team that develops policies for sustainable natural resource utilization.",
    "My job involves creating and implementing strategies for pollution control.",
    "I assist in the development of programs that promote environmental sustainability in the corporate sector.",
    "I'm part of initiatives that aim to mitigate the impacts of industrial activities on the environment.",
    "I work on projects that promote conservation and sustainable use of marine resources.",
    "I assist in the design and implementation of systems for efficient water use and conservation.",
    "My role involves conducting research on the socio-economic impacts of environmental conservation projects.",
    "I work with community groups to develop and implement environmental conservation initiatives.",
    "I'm involved in the planning and execution of projects aimed at combating desertification and land degradation.",
    "I assist in the development of strategies for the conservation of threatened species and their habitats.",
    "I work on initiatives that promote the sustainable management of forests and other important ecosystems.",
    "I assist in the monitoring and evaluation of environmental conservation projects to ensure their effectiveness.",
    "My job involves advocating for policies that support environmental conservation and sustainability.",
    "I help in the development of technologies that promote energy efficiency and reduce greenhouse gas emissions.",
    "I'm involved in the planning and implementation of projects that aim to improve air quality in urban areas.",
    "I work with stakeholders to develop strategies for sustainable wildlife management and conservation.",
    "I assist in the preparation of reports and publications on the outcomes of environmental conservation projects.",
    "My role involves providing technical support to community-based environmental conservation initiatives.",
    "I work on projects that aim to enhance the resilience of communities to the impacts of climate change.",
    "I assist in the development and implementation of educational programs on environmental conservation for various audiences.",
    "I'm involved in the coordination of activities for environmental conservation awareness campaigns and events.",
    "I work with partners to mobilize resources for the implementation of environmental conservation projects.",
    "I assist in the monitoring of environmental quality indicators to inform conservation planning and decision-making.",
    "My job involves providing support to research activities related to environmental conservation and sustainability.",
    "Spent the day planting trees for the new community park, feels good!",
    "Cleaning up the local beach this weekend, so much plastic to pick up!",
    "Working at the wildlife rehab center, got to feed baby raccoons today!",

    # ecology scientists and students
    "I'm researching the impact of invasive species on native wildlife.",
    "I study the effects of pollutants on aquatic life in freshwater lakes.",
    "I am conducting a study on the effects of urbanization on local biodiversity.",
    "My research focuses on the impact of climate change on marine ecosystems.",
    "I am working on a thesis about sustainable agricultural practices and their benefits.",
    "Currently, I am researching the role of pollinators in maintaining ecosystem balance.",
    "I am involved in a project studying the effects of deforestation on wildlife habitats.",
    "My dissertation explores the relationship between air quality and public health.",
    "I am analyzing data on the migration patterns of endangered bird species.",
    "My research group is studying the impact of invasive species on native flora and fauna.",
    "I am developing a model to predict the effects of pollution on freshwater ecosystems.",
    "Currently, I am investigating the role of wetlands in carbon sequestration.",
    "I am conducting experiments to understand the effects of microplastics on marine life.",
    "My research focuses on the conservation of endangered plant species in urban environments.",
    "I am studying the impact of industrial activities on soil quality and fertility.",
    "I am working on a project that explores the relationship between urban green spaces and mental health.",
    "My research involves assessing the effectiveness of conservation policies on protecting biodiversity.",
    "I am investigating the effects of climate change on the distribution of plant and animal species.",
    "Currently, I am studying the role of forests in mitigating the impacts of climate change.",
    "I am conducting a survey to understand public perception and awareness about environmental conservation.",
    "My research explores the impact of habitat fragmentation on the genetic diversity of wildlife.",
    "I am working on developing technologies for efficient and sustainable waste management.",
    "I am studying the effects of chemical pollutants on the health of aquatic organisms.",
    "My research involves modeling the impacts of climate change on agricultural productivity.",
    "I am investigating the role of environmental education in promoting conservation awareness among youth.",
    "Currently, I am researching the impact of noise pollution on the behavior of urban wildlife.",
    "I am conducting experiments to understand the physiological responses of plants to different environmental stressors.",
    "My research focuses on the development of renewable energy technologies to reduce greenhouse gas emissions.",
    "I am studying the impact of land use change on the hydrological dynamics of watersheds.",
    "I am working on a project that assesses the vulnerability of coastal communities to sea-level rise.",
    "My research involves analyzing the socio-economic impacts of environmental degradation on rural populations.",
    "I am investigating the effects of climate variability on the phenology of plant and animal species.",
    "Currently, I am studying the role of community participation in promoting sustainable natural resource management.",
    "I am conducting a study to understand the impact of ecotourism on wildlife behavior and habitat.",
    "My research explores the relationship between environmental conservation and economic development.",
    "I am working on developing strategies for the sustainable management of fisheries.",
    "I am studying the effects of urban heat islands on the health and well-being of residents.",
    "My research involves assessing the impact of conservation interventions on the livelihoods of local communities.",
    "I am investigating the role of traditional knowledge in promoting biodiversity conservation.",
    "Currently, I am researching the impact of climate change on the incidence and distribution of vector-borne diseases.",
    "I am conducting experiments to understand the adaptive mechanisms of plants to changing environmental conditions.",
    "My research focuses on the development of indicators for monitoring and evaluating the success of conservation projects.",
    "I am studying the impact of environmental policies on the sustainability of small-scale farming systems.",
    "I am working on a project that explores the potential of urban farming in promoting food security.",
    "My research involves analyzing the impact of mining activities on the quality of surrounding water bodies.",
    "I am investigating the effects of habitat loss on the population dynamics of endangered species.",
    "Currently, I am studying the role of environmental governance in promoting sustainable development.",
    "Diving deep into marine bio homework, the ocean's complexity is mind-blowing!",
    "In the lab studying soil samples, these tiny organisms do so much!",
    "Field trip to the forest reserve tomorrow, ready to hug some trees and take notes!",

    # space workers
    "I assist in the assembly of satellite components.",
    "My job is to weld parts for spacecraft.",
    "I handle the calibration of space navigation instruments.",
    "I work on the installation of communication devices in satellites.",
    "I'm responsible for the maintenance of rocket launch pads.",
    "I assist in the testing of space exploration robotics.",
    "I operate machinery for the production of space vehicle parts.",
    "I'm involved in the packaging and shipping of aerospace products.",
    "I work on the assembly line producing parts for space shuttles.",
    "I assist engineers in developing prototypes for new space gear.",
    "I conduct quality assurance tests on space mission equipment.",
    "I'm a technician repairing devices used in space stations.",
    "I help in the fabrication of lightweight materials for spacecraft.",
    "I provide support in the control room during satellite launches.",
    "I work in a lab that tests the durability of space suits.",
    "I'm responsible for monitoring the functionality of space rovers.",
    "I assist in the troubleshooting of issues with space mission controls.",
    "I handle the documentation and inventory of aerospace components.",
    "I work on improving the efficiency of satellite signal transmission.",
    "I participate in the construction of modules for international space stations.",
    "I'm on the team that inspects and repairs satellite solar panels.",
    "I assist in the loading and unloading of spacecraft cargo.",
    "I work on the design and manufacturing of space vehicle chassis.",
    "I'm involved in the assembly and disassembly of space mission simulators.",
    "I handle the tools and equipment used in aerospace manufacturing.",
    "I assist in the planning and execution of satellite launch schedules.",
    "I work on the development and testing of space food packaging.",
    "I'm responsible for the safety protocols during rocket testing.",
    "I assist in the analysis and interpretation of satellite data.",
    "I work on the creation and maintenance of space mission databases.",
    "I'm involved in the training and preparation of astronauts for space walks.",
    "I handle the logistics and coordination of space mission supplies.",
    "I work on the programming and operation of satellite trajectory software.",
    "I'm responsible for the installation and testing of space vehicle engines.",
    "I assist in the research and development of new aerospace materials.",
    "I work on the design and fabrication of space vehicle interiors.",
    "I'm involved in the testing and validation of new satellite technologies.",
    "I handle the operation and maintenance of space mission communication systems.",
    "I work on the assembly and testing of space vehicle propulsion systems.",
    "I assist in the development and implementation of space mission training programs.",
    "Got a gig at the planetarium, guiding folks through the stars!",
    "Building satellites ain't easy, but someone's gotta do it!",
    "Launching rockets at the space center today, fingers crossed!",
    "Fixing space suits, preparing astronauts for the big journey!",
    "Working late at the telescope factory, crafting lenses for clear sky views!",
    "Installing solar panels on satellites, harnessing the sun's power!",
    "Maintaining the space shuttle, it's older than me but still going strong!",
    "On duty at the space museum, inspiring the next generation of explorers!",
    "Assembling parts for the international space station, precision is key!",
    "Monitoring satellite signals, keeping an eye on Earth from above!",

    # space scientists and students
    "I'm conducting research on the effects of zero gravity on the human body.",
    "Currently working on a thesis about sustainable life support systems in space.",
    "I'm developing algorithms for efficient satellite data processing and analysis.",
    "My research focuses on studying the atmospheres of different planets.",
    "I'm investigating the possibilities of using asteroids as future space stations.",
    "Working on a project to improve the accuracy of satellite navigation systems.",
    "I'm studying the impact of space travel and planets stuff.",
    "My work involves analyzing the composition of different celestial bodies and gravity.",
    "I'm researching advanced propulsion systems for interstellar travel.",
    "Currently working on the development of new materials for spacecraft construction.",
    "I'm studying the feasibility of establishing permanent colonies on Mars.",
    "My research involves the exploration and mapping of unknown areas of space.",
    "I'm working on improving the efficiency of energy consumption in spacecraft.",
    "Studying the effects of prolonged exposure to space on various organisms.",
    "I'm developing new technologies for deep space communication.",
    "My work focuses on the design and testing of robotic systems for space exploration.",
    "I'm researching the potential of harnessing renewable energy sources in space.",
    "Currently investigating the mysteries of dark matter and dark energy.",
    "I'm working on creating simulations to predict the behavior of galaxies.",
    "My research involves studying the formation and evolution of stars.",
    "I'm developing new techniques for the detection and study of exoplanets.",
    "Working on a project to understand the origins of the universe.",
    "I'm studying the potential of mining valuable resources from asteroids.",
    "My work involves the development of technologies for waste management in space.",
    "I'm researching the possibilities of terraforming planets for human habitation.",
    "Currently working on improving the durability and functionality of space suits.",
    "I'm studying the impact of cosmic radiation on spacecraft and astronauts.",
    "My research focuses on the development of artificial intelligence for space missions.",
    "I'm working on the design and construction of telescopes for space observation.",
    "Studying the physics and dynamics of black holes and neutron stars.",
    "I'm developing new methods for the prevention and mitigation of space debris.",
    "My work involves the analysis and interpretation of data from space probes.",
    "I'm researching the potential applications of quantum mechanics in space technology.",
    "Currently working on the development of instruments for space weather forecasting.",
    "I'm studying the biological and chemical processes that occur in space.",
    "My research involves the exploration and study of the moon's surface and composition.",
    "I'm working on the design and testing of equipment for space medical emergencies.",
    "Studying the potential of using space technology for climate monitoring and prediction.",
    "I'm developing new methodologies for the study and exploration of the solar system.",
    "My work focuses on the improvement of living conditions in space habitats.",
    "I'm researching the effects of space environment on different materials.",
    "Currently working on the development of technologies for space farming and agriculture.",
    "I'm studying the principles and applications of space law and policy.",
    "My research involves the design and optimization of space mission trajectories.",
    "I'm working on the development and testing of microgravity research equipment.",
    "Studying the potential of using space technologies for disaster management and relief.",
    "Stargazing tonight for my astronomy class, can't wait to spot some constellations!",
    "Diving deep into my astrophysics coursework, black holes are mind-blowing, planets too!",
    "Working on my thesis about Martian landscapes, so much to explore and discover!",
    "Just got access to the observatory for my research, the universe is calling!",

    # health workers
    "I work at a community health center providing support to patients.",
    "My job involves organizing health awareness campaigns in schools.",
    "I assist in the administration of vaccines at a local clinic.",
    "Working in a pharmaceutical company, I help in the production of medications.",
    "I'm employed at a fitness center, promoting physical health and well-being.",
    "My daily tasks involve providing care to elderly individuals at a nursing home.",
    "I work in a hospital's administrative department, ensuring smooth operations.",
    "As a technician, I assist in the operation of medical imaging devices.",
    "I'm involved in the distribution of essential medical supplies to clinics.",
    "My job is to ensure the cleanliness and sanitation of a healthcare facility.",
    "I work in a dental office assisting dentists during procedures.",
    "My role involves providing mental health support to individuals in need.",
    "I assist in conducting health screenings and tests at a diagnostic center.",
    "Working in a laboratory, I help with the processing of medical samples.",
    "I'm employed in a rehabilitation center aiding patients in their recovery.",
    "My job involves promoting nutritional health through diet planning and advice.",
    "I work in the field of occupational health, ensuring workplace safety.",
    "As a healthcare worker, I provide home care services to patients.",
    "I assist in the management of health records and patient data at a clinic.",
    "My role involves supporting the work of healthcare professionals in a hospital.",
    "I work in a pharmacy assisting in the dispensing of prescription medications.",
    "My job is to promote sexual health education and services in the community.",
    "I assist in the provision of eye care services at an optometry clinic.",
    "Working in the field of public health, I help implement community health initiatives.",
    "I'm involved in providing support to individuals struggling with addiction.",
    "My work focuses on promoting maternal and child health in underserved communities.",
    "I assist in the operation and maintenance of medical equipment in hospitals.",
    "As a healthcare worker, I support patients undergoing cancer treatment.",
    "I work in a research lab assisting in health-related studies and experiments.",
    "My job involves providing care and support to individuals with disabilities.",
    "I work in a hospital's emergency department assisting in patient care.",
    "My role is to help patients navigate the healthcare system and access services.",
    "I assist in the planning and execution of health promotion events and activities.",
    "Working in a clinic, I help provide healthcare services to children and families.",
    "I'm involved in the training and education of community health workers.",
    "My work focuses on improving access to healthcare in rural and remote areas.",
    "I assist in the development and implementation of health policies and programs.",
    "As a worker in the health sector, I support research and development initiatives.",
    "I work in a hospice providing end-of-life care to patients and support to families.",
    "My job involves assisting in surgical procedures and post-operative care.",
    "I work in the field of environmental health, monitoring and addressing public health risks.",
    "My role involves supporting individuals and families dealing with chronic illnesses.",
    "Just finished a long shift at the clinic, so many flu shots given out today!",
    "Working at the pharmacy and helping folks understand their meds better.",
    "Busy day ahead at the health center, lots of patients to care for!",
    "Helping out at the dental office today, smiles everywhere!",
    "On the grind at the hospital, making sure patients are comfy and cared for.",
    "Working the night shift at the nursing home, bringing smiles and meds!",
    "Spent the day assisting in surgeries, saving lives one operation at a time!",
    "Delivering meals to patients today, everyone needs some good nourishment!",

    # health scientists and students
    "I'm conducting research on the development of new vaccines and treatments.",
    "As a medical student, I'm learning about various diseases and their management.",
    "I'm involved in a study exploring the mental health impacts of social isolation.",
    "My research focuses on understanding the genetic factors influencing health.",
    "I'm working on a project to improve access to healthcare in underserved communities.",
    "As a public health student, I'm studying the effects of environmental factors on health.",
    "I'm researching innovative approaches to health education and promotion.",
    "My work involves analyzing health policies and their impact on population health.",
    "I'm conducting a study to understand the health needs of elderly individuals.",
    "As a nursing student, I'm learning about patient care and healthcare systems.",
    "I'm involved in research on the prevention and management of chronic diseases.",
    "My study focuses on the development of telemedicine and digital health solutions.",
    "I'm researching the social determinants of health and health disparities.",
    "As a pharmacy student, I'm studying pharmacology and medication management.",
    "I'm working on a project to improve maternal and child health outcomes.",
    "My research involves the study of infectious diseases and epidemiology.",
    "I'm conducting a study on the impact of nutrition and diet on health.",
    "As a dental student, I'm learning about oral health and dental procedures.",
    "I'm involved in research on mental health interventions and therapies.",
    "My work focuses on the development of medical devices and technologies.",
    "I'm studying the effects of exercise and physical activity on health.",
    "As a health sciences student, I'm exploring various aspects of healthcare and medicine.",
    "I'm researching the impact of healthcare policies on patient care and outcomes.",
    "My study involves the analysis of health data and healthcare informatics.",
    "I'm working on a project to understand the health impacts of climate change.",
    "As a medical research student, I'm studying the mechanisms of diseases.",
    "I'm involved in the development of health promotion and prevention programs.",
    "My research focuses on understanding the biology of cancer and potential treatments.",
    "I'm studying the effects of stress and anxiety on physical and mental health.",
    "As a healthcare management student, I'm learning about healthcare administration.",
    "I'm conducting research on the effectiveness of various healthcare interventions.",
    "My work involves the study of healthcare quality and patient safety.",
    "I'm researching the impact of technology on healthcare delivery and patient care.",
    "As a biomedical student, I'm studying the principles of medical research and diagnostics.",
    "I'm involved in a study exploring the health impacts of pollution and environmental toxins.",
    "My research focuses on the development and evaluation of health communication strategies.",
    "I'm studying the role of healthcare professionals in improving patient outcomes.",
    "As a health policy student, I'm analyzing the implications of health regulations and laws.",
    "I'm conducting a study on the health behaviors and lifestyles of different populations.",
    "My work involves researching the impact of social and economic factors on health.",
    "I'm researching the effectiveness of alternative and complementary medicine practices.",
    "As a clinical research student, I'm learning about the design and conduct of clinical trials.",
    "I'm involved in a project to improve the health and well-being of individuals with disabilities.",
    "Diving deep into medical journals tonight, gotta unlock the secrets of these new viruses!",
    "In the lab, brewing up some potential cures. Fingers crossed!",
    "Studying the effects of diet on mental health, and it's mind-blowing stuff!",
    "Late night in the bio lab, studying cell regeneration. Science is wild!",
    "Cracking the books on genetic disorders today. So much to learn!",
    "Experimenting with new health tech to monitor patient vitals remotely. The future is now!",
    "Working on a thesis about the impact of exercise on chronic diseases. Sweat is just fat crying, right?",

    # climate workers
    "I work on installing and maintaining renewable energy systems to combat climate change.",
    "My job involves analyzing climate data to help companies reduce their carbon footprint.",
    "I work with communities to develop and implement climate adaptation strategies.",
    "I'm involved in afforestation projects to mitigate the effects of climate change.",
    "My work focuses on promoting sustainable practices to address climate challenges.",
    "I engage in environmental advocacy to raise awareness about climate change.",
    "I work on developing technologies for efficient energy use and climate mitigation.",
    "My job involves planning and managing projects for climate resilience in cities.",
    "I work with scientists to translate climate research into actionable policies.",
    "I'm involved in initiatives to promote sustainable transportation to reduce emissions.",
    "My work focuses on educating the public about the impacts of climate change.",
    "I engage in conservation work to protect biodiversity threatened by climate change.",
    "I work on projects to improve water management in the face of climate variability.",
    "My job involves designing infrastructure resilient to extreme climate events.",
    "I work with businesses to implement practices that contribute to climate solutions.",
    "I'm involved in policy advocacy to advance climate action at various levels.",
    "My work focuses on developing and promoting renewable energy sources.",
    "I engage in community outreach to promote climate awareness and action.",
    "I work on initiatives to improve waste management and recycling for sustainability.",
    "My job involves researching and developing climate-friendly products and services.",
    "I work with NGOs to implement projects addressing climate-related challenges.",
    "I'm involved in efforts to restore and protect ecosystems affected by climate change.",
    "My work focuses on assisting communities affected by climate-induced disasters.",
    "I engage in activities to promote energy conservation and efficiency.",
    "I work on developing strategies for sustainable agriculture in a changing climate.",
    "My job involves conducting assessments of climate risks and vulnerabilities.",
    "I work with governments to develop and implement climate action plans.",
    "I'm involved in campaigns to promote climate justice and equity.",
    "My work focuses on supporting research on climate solutions and technologies.",
    "I engage in efforts to reduce air pollution and improve environmental health.",
    "I work on projects to enhance the sustainability of urban and rural development.",
    "My job involves advising companies on integrating sustainability into their operations.",
    "I work with educators to incorporate climate education into curricula.",
    "I'm involved in initiatives to promote conservation and sustainable use of natural resources.",
    "My work focuses on facilitating cooperation on climate action among different stakeholders.",
    "I engage in public speaking and writing to advocate for urgent climate action.",
    "I work on creating and disseminating content to raise climate awareness.",
    "My job involves organizing and participating in events promoting climate solutions.",
    "I work with researchers to apply climate science in decision-making and planning.",
    "I'm involved in efforts to enhance the resilience of supply chains to climate impacts.",
    "My work focuses on developing tools and resources for climate education and communication.",
    "Just installed some new solar panels at work, doing our bit to fight climate change!",
    "Planting trees today at work, because Mother Earth needs more green!",
    "Busy day ahead, working on setting up a community garden to promote sustainability.",
    "Got my hands dirty creating a rain garden at work to reduce stormwater runoff!",
    "Helping businesses reduce their carbon footprint is all in a day's work for me.",
    "Spent the day weatherizing homes to save energy and combat climate change!",
    "Working hard to improve public transit options, because fewer cars mean cleaner air!",
    "Installing wind turbines today, harnessing that powerful breeze for clean energy!",
    "At work, turning waste into energy and feeling like a climate change superhero!",

    # climate scientists and students
    "I am researching the impact of climate change on polar ice melt and sea level rise.",
    "My study focuses on the effects of global warming on biodiversity and ecosystems.",
    "I am investigating the role of deforestation in altering the Earth's climate.",
    "My research involves analyzing the effectiveness of renewable energy sources in reducing carbon emissions.",
    "I am studying the influence of climate change on the frequency and intensity of extreme weather events.",
    "My work is centered on understanding the social and economic impacts of climate change.",
    "I am exploring innovative technologies for carbon capture and storage.",
    "My research aims to understand the relationship between climate change and human health.",
    "I am working on developing models to predict future climate scenarios and their implications.",
    "My study involves assessing the vulnerability and resilience of communities to climate change.",
    "I am investigating the effects of climate change on water resources and availability.",
    "My research focuses on the impact of rising temperatures on agriculture and food security.",
    "I am studying the role of oceans in regulating the Earth's climate.",
    "My work involves analyzing policies and regulations related to climate change mitigation and adaptation.",
    "I am researching ways to enhance energy efficiency and sustainability in various sectors.",
    "My study is focused on understanding the dynamics of the Earth's atmosphere and climate.",
    "I am working on projects that aim to promote environmental conservation and sustainability.",
    "My research involves studying the impact of climate change on wildlife and natural habitats.",
    "I am investigating strategies for sustainable urban planning in the context of climate change.",
    "My study involves examining the psychological and behavioral aspects of climate change perception and action.",
    "I am researching the potential of geoengineering solutions to counteract climate change.",
    "My work focuses on analyzing the carbon footprint of different industries and practices.",
    "I am studying the impact of climate change on the spread and intensity of infectious diseases.",
    "My research involves developing and testing materials and technologies for green building.",
    "I am working on understanding the implications of climate change for international security and cooperation.",
    "My study focuses on the ethical and equity considerations in climate change policy and action.",
    "I am researching the role of education and communication in promoting climate change awareness and action.",
    "My work involves studying the effects of climate change on economic development and poverty reduction.",
    "I am investigating the potential of sustainable transportation solutions to reduce greenhouse gas emissions.",
    "My research is focused on understanding the interactions between climate change and other global challenges.",
    "I am studying the impact of climate change on mental health and well-being.",
    "My work involves developing methodologies for climate risk assessment and management.",
    "I am researching the influence of climate change on migration and displacement patterns.",
    "My study is centered on understanding the role of policy and governance in addressing climate change.",
    "I am working on projects that explore the potential of nature-based solutions for climate mitigation and adaptation.",
    "My research involves analyzing public opinion and political discourse on climate change.",
    "I am investigating the impact of climate change on the availability and distribution of natural resources.",
    "My study focuses on the development and evaluation of climate change adaptation strategies for vulnerable populations.",
    "I am researching the effectiveness of international agreements and initiatives on climate change.",
    "My work is focused on studying the impact of climate change on indigenous communities and their livelihoods.",
    "I am working on understanding the drivers and consequences of climate-induced changes in biodiversity.",
    "My research involves developing tools and technologies for monitoring and reporting greenhouse gas emissions.",
    "I am studying the impact of climate change on the quality and safety of food products.",
    "My work involves analyzing the effectiveness of economic instruments for climate change mitigation and adaptation.",
    "I am researching the role of innovation and entrepreneurship in promoting climate action and sustainability.",
    "My study is focused on understanding the impact of climate change on infrastructure and built environment.",
    "I'm diving deep into climate studies, trying to figure out how we can chill with the rising temps!",
    "Just exploring how these crazy hurricanes are getting pumped by climate change. Research mode on!",
    "Working on my thesis about how climate change is messing with our beloved coffee beans. The struggle is real!",
    "Studying glaciers today. They're like, 'We're melting!', and I'm like, 'Hold on, I'm trying to save you!'"
])

occupation_labels = []

# adding 50 workers
worker_label = {"cats": {"Worker": 1.0, "Scientist": 0.0}}
occupation_labels.extend([worker_label] * 50)

# adding 50 scientists
scientist_label = {"cats": {"Worker": 0.0, "Scientist": 1.0}}
occupation_labels.extend([scientist_label] * 50)

# repeting the process as needed
occupation_labels.extend([worker_label] * 50)
occupation_labels.extend([scientist_label] * 50)
occupation_labels.extend([worker_label] * 50)
occupation_labels.extend([scientist_label] * 50)
occupation_labels.extend([worker_label] * 50)
occupation_labels.extend([scientist_label] * 50)

field_labels = []

# adding 100 ecology
ecology_label = {"cats": {"Ecology": 1.0,
                          "Space": 0.0, "Health": 0.0, "Climate": 0.0}}
field_labels.extend([ecology_label] * 100)

# adding 100 space
space_label = {"cats": {"Ecology": 0.0,
                        "Space": 1.0, "Health": 0.0, "Climate": 0.0}}
field_labels.extend([space_label] * 100)

# adding 100 health
health_label = {"cats": {"Ecology": 0.0,
                         "Space": 0.0, "Health": 1.0, "Climate": 0.0}}
field_labels.extend([health_label] * 100)

# adding 100 climate
climate_label = {"cats": {"Ecology": 0.0,
                          "Space": 0.0, "Health": 0.0, "Climate": 1.0}}
field_labels.extend([climate_label] * 100)
