management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,metrics,env,prometheus
---
spring:
  config:
    activate:
      on-profile: default
  application:
    name: scisight


api:
  nasa:
    url:
    token:
  weather:
    url: api.weather.gov
    token:
